apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  uptrends-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: uptrends-controller
subjects:
- kind: ServiceAccount
  name: uptrends-controller
  namespace: uptrends
