apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptrends-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: uptrends-controller
  serviceName: uptrends-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: uptrends-controller
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: uptrends-controller
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/part-of: uptrends
              topologyKey: kubernetes.io/hostname
            weight: 5
      containers:
      - command:
        - /main
        image: ghcr.io/ionos-cloud/uptrends/operator:v0.0.1
        name: operator
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      terminationGracePeriodSeconds: 10
      serviceAccountName: uptrends-controller
