apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "uptrends.controllerServiceAccountName" . }}
  labels:
    {{- include "uptrends.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
  {{- range $key, $value := .Values.controller.serviceAccount.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
