# permissions for end users to view uptrends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uptrends-viewer-role
rules:
- apiGroups:
  - uptrends.ionos-cloud.github.io
  resources:
  - uptrends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - uptrends.ionos-cloud.github.io
  resources:
  - uptrends/status
  verbs:
  - get
